### ISSUE TITLE
Chapter 3 material

### ISSUE THREAD

**Issue by Neo-Hao** [Neo-Hao/database-design-from-scratch#7]
I don't think the chapter 3 material is of a quality that's high enough for it to be useful to readers. I don't have the time to revise this. I doubt if you have the capacity to revise this sufficiently either. I would recommend getting rid of it. Any thoughts?

**Comment by tsikerdekis** [comment]
Given that it is not a high priority, we could aim to develop it further later on after the main book writing is done. I was hoping to generate additional data in order for it to be a bit more realistic doc but at the moment not a high priority.
